name: CI for ubuntu Setup
on:

  push:
    branches: [ master ]

  # Release
  release:
      types: [published]
  workflow_dispatch:
jobs:
  # Renamed job for clarity
  validate-ubuntu-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache models and tools
        uses: actions/cache@v4
        with:
          path: |
            ./tools/
            ./LanguageTool-6.6
            ./models/
          key: ${{ runner.os }}-models-tools-${{ hashFiles('**/setup/*.sh') }}
          restore-keys: |
            ${{ runner.os }}-models-tools-
          
      - name: Update apt repositories
        run: sudo apt-get update -y

      - name: Run ubuntu_setup.sh
        run: bash ./setup/ubuntu_setup.sh

      - name: Package Assets as Artifact(90days available from last run of this workflow)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sl5-assets-pack-ubuntu
          path: |
            ./LanguageTool-6.6
            ./models/
